
/*const importAll = r => {
    let images = {};
    r.keys().map((item, index) => { return images[item.replace('./', '')] = r(item); });
    return images;
}
const images = importAll(require.context('./assets/foodImages', false, /\.(png|jpg|svg)$/));*/

const productData = [
    {
        id: 1,
        img: "https://dl.dropboxusercontent.com/s/en396t8jgwhmqja/green%20chili.jpg?dl=0",
        title: 'Green Chili-250g',
        desc: "Green chili peppers widely vary in size and shape, appearing slightly curved to straight, and can contain different levels of spice depending on the individual variety.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 2,
        img: "https://dl.dropboxusercontent.com/s/9hktt0rrj0fffhs/cucumber.jpg?dl=0",
        title: 'Hybrid Cucumber-500g',
        desc: "Cucumber is a summer vegetable, with elongate shape and 15cm long. Its skin is of a green colour, turning into yellow in maturation.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 3,
        img: "https://dl.dropboxusercontent.com/s/tcjvge99vwa0z1y/onion.jpg?dl=0",
        title: 'Onion-1kg',
        desc: 'Onions are cultivated and used around the world. As a food item, they are usually served cooked, as a vegetable or part of a prepared savoury dish, but can also be eaten raw ',
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 4,
        img: "https://dl.dropboxusercontent.com/s/xpe7cwnahtwut84/okra.jpg?dl=0",
        title: 'Okra-500g',
        desc: "Okra grows in an elongated, lantern shape vegetable. It is a fuzzy, green colored, and ribbed pod that is approximately 2-7 inches in length.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 5,
        img: "https://dl.dropboxusercontent.com/s/ia8rbezmj0qtrie/lemon.jpg?dl=0",
        title: 'Lemon-4pcs',
        desc: "The lemon is a round, slightly elongated fruit, it has a strong and resistant skin, with an intense bright yellow colour when it is totaly ripe, giving off a special aroma when it is cut",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 6,
        img: "https://dl.dropboxusercontent.com/s/bqtlt9q9lsqheie/mint.jpg?dl=0",
        title: 'Mint Leaves-100g',
        desc: "Mint Leaves are produced from good quality, cleaned dried leaves of Mentha viridas and are dark green in colour with a strong clean sweet menthol flavour profile",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 7,
        img: "https://dl.dropboxusercontent.com/s/w3kbulzanb51woz/sweet%20potato.jpg?dl=0",
        title: 'Sweet Potato-1kg',
        desc: '',
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 8,
        img: "https://dl.dropboxusercontent.com/s/f0q0542uv857vpl/pumpkin.jpg?dl=0",
        title: 'Pumpkin-1slice',
        desc: "A pumpkin is a cultivar of winter squash that is round with smooth, slightly ribbed skin, and is most often deep yellow to orange in coloration. ",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 9,
        img: "https://dl.dropboxusercontent.com/s/cenhs1qd3aunp5z/potato.jpg?dl=0",
        title: 'Potato-1kg',
        desc: "The potato is a tuber, round or oval, with small white roots called eyes, that are growth buds. The size varies depending on the variety; the colour of the skin can be white, yellow or even purple. ",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 10,
        img: "https://dl.dropboxusercontent.com/s/ri1rbsdtrmotp2t/papaya.jpg?dl=0",
        title: 'Green Papaya-1kg',
        desc: "The Green papaya fruit weighs an average of one to two pounds. It is pear-shaped with a true green peel and a pale translucent yellow-green flesh that bears a pocket of seeds in its central core. The flesh and the seeds are the edible part of the fruit.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 11,
        img: "https://dl.dropboxusercontent.com/s/uz37fxx0avqysno/eggplant.jpg?dl=0",
        title: 'Eggplant',
        desc: "The stem is often spiny. The flowers are white to purple in color, with a five-lobed corolla and yellow stamens.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 12,
        img: "https://dl.dropboxusercontent.com/s/oljq1icabkrscv6/banana.jpg?dl=0",
        title: 'Green Banana-4pcs',
        desc: "Green bananas are raw bananas, which are quite firm in texture. They are at their immature stage where they have not yet ripened.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 13,
        img: "https://dl.dropboxusercontent.com/s/8p95js4cdymhdnx/carrot.jpg?dl=0",
        title: 'Carrot-500g',
        desc: "Carrot is a biennial, belonging to the family Apiaceae, and is an important vegetable for its fleshy edible, colorful roots. It varies in colour from white, yellow, orange, light purple, deep red to deep violet.",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 14,
        img: "https://dl.dropboxusercontent.com/s/926mkb1acj97c35/red%20chilli.jpg?dl=0",
        title: 'Red Chilli-200g',
        desc: "Dried red chilli powder is a major food ingredient in Indian and international cuisines. Red chilli powder brings its characteristic bright red color and pungency to any preparation it is used in",
        category: 'Vegetables',
        price: 46,
    },
    {
        id: 15,
        img: "https://dl.dropboxusercontent.com/s/9sr8qzgaqizrgju/coco%20powder.jpg?dl=0",
        title: 'Coco Powder-500gm',
        desc: "Coco powder is the fine ground brown powder obtained from the partially or completely defatted portion of cocoa liquor or mass of fermented cocoa beans",
        category: 'Baking Needs',
        price: 300,
    },
    {
        id: 16,
        img: "https://dl.dropboxusercontent.com/s/vif656ymgq6klg7/baking.jpg?dl=0",
        title: 'Baking Powder-250gm',
        desc: "Baking soda, also known as bicarbonate of soda or sodium bicarbonate, is a chemical leavening agent commonly used in baked goods. Baking soda is a base alkaline compound, which means it is not acidic",
        category: 'Baking Needs',
        price: 110,
    },
    {
        id: 17,
        img: "https://dl.dropboxusercontent.com/s/h2mjvghh8eii21b/salt.jpg?dl=0",
        title: 'Salt -1kg',
        desc: "Salt is an important natural preservative and has been used for centuries to preserve meat, fish, dairy products and many other foods.",
        category: 'Daily cooking',
        price: 35,
    },
    {
        id: 18,
        img: "https://dl.dropboxusercontent.com/s/u555gc1xhf7by2h/lentils.jpg?dl=0",
        title: 'Mixed Lentils-1kg',
        desc: "garlib and herbs mix is a mix of 4-5 different types of lentils. Commonly used in curries, it has a high rich protein content and is very healthy.",
        category: 'Daily cooking',
        price: 150,
    },
    {
        id: 19,
        img: "https://dl.dropboxusercontent.com/s/f5qeszpr0rqnjxy/gorom%20masala.jpg?dl=0",
        title: 'Gorom Masala-100gm',
        desc: "Garam masala is a spice blend widely used in Indian cuisine, from curries and lentil dishes to soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds, cumin seeds, and cardamon pods are toasted in a pan to release their aromatic flavors, then ground to a powder",
        category: 'Daily cooking',
        price: 60,
    },
    {
        id: 20,
        img: "https://dl.dropboxusercontent.com/s/kb52bkyjyqg284e/basmati%20rice.jpg?dl=0",
        title: 'Basmati Rice-1kg',
        desc: 'Basmati Rice is selected from high quality rice. The health advantages of rice is its ability to produce and keep instant energy. ',
        category: 'Daily cooking',
        price: 200,
    },
    {
        id: 21,
        img: "https://dl.dropboxusercontent.com/s/m8dhjohumcdk8eh/rice.jpg?dl=0",
        title: 'Natural Minicate Rice-5kg',
        desc: 'Natural Minicate Rice is selected from high quality rice. The health advantages of rice is its ability to produce and keep instant energy. ',
        category: 'Daily cooking',
        price: 410,
    },
    {
        id: 22,
        img: "https://dl.dropboxusercontent.com/s/aak1j30y50drp2n/milk%20powder.jpg?dl=0",
        title: 'Milk powder-400gm',
        desc: "Goalini Fortified contains high quality protein which helps to develop overall growth . It contains vitamins and several minerals in the making . It is consisted of essential amino acids that everyone need.",
        category: 'Dairy',
        price: 350,
    },
    {
        id: 23,
        img: "https://dl.dropboxusercontent.com/s/garuptqgb9r8xjb/milk.jpg?dl=0",
        title: 'FarmFresh Milk- 1 Litre',
        desc: "FarmFresh Pasteurized Milk is collected from homestead dairy farmers across Bangladesh everyday, the milk is being pasteurized to make it germ free, healthy, fresh-testing and flavorful.",
        category: 'Dairy',
        price: 65,
    },
    {
        id: 24,
        img: "https://dl.dropboxusercontent.com/s/o9auosvpwrs1mre/yougurt.jpg?dl=0",
        title: 'Sweet Yougurt-1kg',
        desc: "Made from pasteurized toned milk and active culture, contains 3 percent fat, thick and natural taste.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 90,
    },
    {
        id: 25,
        img: "https://dl.dropboxusercontent.com/s/a07ek39h8a7yo6h/chocolate.jpg?dl=0",
        title: 'Dark chocolate-60gm',
        desc: 'Relish happy moments with your loved ones with a Cadbury Dairy Milk Chocolate block.',
        category: 'Chocolate and candy',
        price: 160,
    },
    {
        id: 26,
        img: "https://dl.dropboxusercontent.com/s/k1asq4ub3ay2or6/candies.jpg?dl=0",
        title: '1 packet Candy-100 candies',
        desc: "Cadbury temptations brings you a delicious premium candy in rum and raisin flavour. ",
        category: 'Chocolate and candy',
        price: 150,
    },
    {
        id: 27,
        img: "https://dl.dropboxusercontent.com/s/rn1gc09saq5tmdz/handwash.jpg?dl=0",
        title: 'Dettol Handwash- 500ml',
        desc: "Dettol Handwash protects hands from germs and gives 10 times better protection. Dettol's Trusted Germ Protection formula keeps you healthy and protected from 100 illness causing germs. Use Dettol Liquid Handwash to protect your hands from germs! Comes with a free 50ml Hand Sanitizer too!",
        category: 'Hygiene & essential',
        price: 160,
    },
    {
        id: 28,
        img: "https://dl.dropboxusercontent.com/s/pl7chquay5lm9j4/body%20wash.jpg?dl=0",
        title: 'Dettol Bodywash- 500ml',
        desc: 'Dettol bodywash Original gets us the most cost Effective germ Protection every day . Recommended By The Bangladesh Private Medical Practitioners Association (BPMPA) . It Comes with a classic fragrance and assuring safety from germs and other infection',
        category: 'Hygiene & essential',
        price: 250,
    },
    {
        id: 29,
        img: "https://dl.dropboxusercontent.com/s/tovv0dfuta6jq8w/detol%20soap.jpg?dl=0",
        title: 'Dettol soap',
        desc: "Dettol Soap Original gets us the most cost Effective germ Protection every day . Recommended By The Bangladesh Private Medical Practitioners Association (BPMPA) . It Comes with a classic fragrance and assuring safety from germs and other infection",
        category: 'Hygiene & essential',
        price: 50,
    },
    {
        id: 30,
        img: "https://dl.dropboxusercontent.com/s/9rnvjh58t46py4y/coca%20cola.jpg?dl=0",
        title: 'Coca-cola - 1litre',
        desc: "Coca Cola is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
        category: 'Beverage',
        price: 60,
    },
    {
        id: 31,
        img: "https://dl.dropboxusercontent.com/s/oljq1icabkrscv6/banana.jpg?dl=0",
        title: 'Banana-6pcs',
        desc: "The banana is a lengthy yellow fruit, found in the market in groups of three to twenty fruits, similar to a triangular cucumber, oblong and normally yellow.",
        category: 'Fruits',
        price: 60,
    },
    {
        id: 32,
        img: "https://dl.dropboxusercontent.com/s/102kgp6tix9urb7/orange.jpg?dl=0",
        title: 'Orange-1kg',
        desc: "The orange is a usually round or oval citrus; its rind and flesh are generally orange, except the varieties of red pulp.",
        category: 'Fruits',
        price: 120,
    },
    {
        id: 33,
        img: "https://dl.dropboxusercontent.com/s/ydkdtb6g1vern0s/guava.jpg?dl=0",
        title: 'Guava-1kg',
        desc: "The fruit has a light yellow or pink pulp, is eaten fresh or as preserves, ",
        category: 'Fruits',
        price: 40,
    },
    {
        id: 34,
        img: "https://dl.dropboxusercontent.com/s/hp4uryre4aizx01/apple.jpg?dl=0",
        title: 'Red Apple-1kg',
        desc: "Apples are high in pectin fibre. Apples boost metabolic levels, help improve heart health and regulate body's blood sugar levels by regulating the release of sugar. They are also packed with vitamin and minerals that promote healthy bones, teeth and skin",
        category: 'Fruits',
        price: 120,
    },
    {
        id: 35,
        img: "https://dl.dropboxusercontent.com/s/9mi12drmjnevftl/mango.jpg?dl=0",
        title: 'Green Manago-1kg',
        desc: "This Green mangoes aren't ripe, sweet and very yellow but more raw, tangy, sour and have more bite to them.",
        category: 'Fruits',
        price: 410,
    },
    {
        id: 36,
        img: "https://dl.dropboxusercontent.com/s/317303lmnfw6tl1/pineapple.jpg?dl=0",
        title: 'Pineapple-1pc',
        desc: "Pineapples have yellow or white pulp, fleshy, aromatic, juicy and sweet. In the fruit there is a fibrous axis that extends from the crown to the pedicle.",
        category: 'Fruits',
        price: 30,
    },
    {
        id: 37,
        img: "https://dl.dropboxusercontent.com/s/wokeam1321gnh9n/lycee.jpg?dl=0",
        title: 'Lychee-50pcs',
        desc: "Lychees are round or oblong in shape and are 1 ½ to 2 inches in diameter. Their opaque white flesh is fragrant and sweet, with floral notes",
        category: 'Fruits',
        price: 90,
    },
    {
        id: 38,
        img: "https://dl.dropboxusercontent.com/s/7ksuzlsv25uoug3/pomegranate.jpg?dl=0",
        title: 'Pomegranate-200g',
        desc: "Red-purple in color, the pomegranate fruit husk has two parts: an outer, hard pericarp, and an inner, spongy mesocarp",
        category: 'Fruits',
        price: 100,
    },
    {
        id: 39,
        img: "https://dl.dropboxusercontent.com/s/8fvwmpqx16f1h00/grapes.jpg?dl=0",
        title: 'Grapes-500g',
        desc: "a smooth-skinned juicy light green or deep red to purplish black berry eaten dried or fresh as a fruit or fermented to produce wine.",
        category: 'Fruits',
        price: 240,
    },
    {
        id: 40,
        img: "https://dl.dropboxusercontent.com/s/fdje4eymjn44z71/dates.jpg?dl=0",
        title: 'Dates-500g',
        desc: "Outside the dates are wrinkled but inside they are soft, juicy and sticky. They have a delicious, deep flavor of caramel, so much so that you can not believe you are eating a fruit",
        category: 'Fruits',
        price: 200,
    },
    {
        id: 41,
        img: "https://dl.dropboxusercontent.com/s/6nqyuxigew322aa/fanta.jpg?dl=0",
        title: 'Fanta-1L',
        desc: "Fanta is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
        category: 'Beverage',
        price: 65,
    },
    {
        id: 42,
        img: "https://dl.dropboxusercontent.com/s/1lm1853okca4554/pepsi.jpg?dl=0",
        title: 'Pepsi-1L',
        desc: "Pepsi is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
        category: 'Beverage',
        price: 60,
    },
    {
        id: 43,
        img: "https://dl.dropboxusercontent.com/s/gd9unb8fihdnjd2/dew.png?dl=0",
        title: 'Dew-250ml',
        desc: "Mountain Dew is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
        category: 'Beverage',
        price: 20,
    },
    {
        id: 44,
        img: "https://dl.dropboxusercontent.com/s/rq94bovnwuvblq3/sprite.jpg?dl=0",
        title: 'Sprite-500ml',
        desc: "Sprite is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
        category: 'Beverage',
        price: 35,
    },
    {
        id: 45,
        img: "https://dl.dropboxusercontent.com/s/aih5zeyr770dfs4/dark.jpg?dl=0",
        title: 'Amul Dark Chocolate-200gm',
        desc: "Amul temptations brings you a delicious premium Chocolate in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 150,
    },
    {
        id: 46,
        img: "https://dl.dropboxusercontent.com/s/ypxrjhu4xijgzdx/white.png?dl=0",
        title: 'Amul White Chocolate-200gm',
        desc: "Amul temptations brings you a delicious premium candy in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 180,
    },
    {
        id: 47,
        img: "https://dl.dropboxusercontent.com/s/h8efwsfp7ree0z9/safari.jpg?dl=0",
        title: 'Safari-20gm',
        desc: "Amul temptations brings you a delicious premium candy in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 25,
    },
    {
        id: 48,
        img: "https://dl.dropboxusercontent.com/s/entwz6qcdqnt8dp/kitkat.jpg?dl=0",
        title: 'kit kat-40gm',
        desc: "Kitkat temptations brings you a delicious premium candy in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 60,
    },
    {
        id: 49,
        img: "https://dl.dropboxusercontent.com/s/1s6cot89no0d47u/break.jpg?dl=0",
        title: 'Break-10gm',
        desc: "Break temptations brings you a delicious premium Chocolate in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 15,
    },
    {
        id: 50,
        img: "https://dl.dropboxusercontent.com/s/xicbvkjeqgdtovy/silk.jpg?dl=0",
        title: 'Cadbury Dairy Milk Silk-150gm',
        desc: "Cadbury temptations brings you a delicious premium Chocolate in rum and raisin flavour.",
        category: 'Chocolate and candy',
        price: 150,
    },
    {
        id: 51,
        img: "https://dl.dropboxusercontent.com/s/zpjtado17cjtzx0/chocolatemilk.jpg?dl=0",
        title: 'farmfresh Chocolate Milk-100gm',
        desc: "Made from pasteurized toned milk and active culture, contains 3 percent fat,chocolate, thick and natural taste.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 30,
    },
    {
        id: 52,
        img: "https://dl.dropboxusercontent.com/s/7nhqchsk73t2ksc/elachi.jpg?dl=0",
        title: 'FarmFresh Elachi Milk-150gm',
        desc: "Made from pasteurized toned milk and active culture, contains 3 percent fat,elachi, thick and natural taste.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 35,
    },
    {
        id: 53,
        img: "https://dl.dropboxusercontent.com/s/h2tgy9j8neud0ym/matha.jpg?dl=0",
        title: 'Matha-100gm',
        desc: "Made from yogurt and active culture, contains 3 percent fat, thick and natural taste.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 20,
    },
    {
        id: 54,
        img: "https://dl.dropboxusercontent.com/s/wlq8d8wv2j4ujcg/paneer.jpg?dl=0",
        title: 'Paneer-50gm',
        desc: "Made from fresh milk and active culture, contains 10 percent fat.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 70,
    },
    {
        id: 55,
        img: "https://dl.dropboxusercontent.com/s/6kl67mj8si6scp5/scheese.jpg?dl=0",
        title: 'Slice Cheese-15 piece',
        desc: "Made from fresh milk and active culture, contains 20 percent fat.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
        category: 'Dairy',
        price: 180,
    },
    {
        id: 56,
        img: "https://dl.dropboxusercontent.com/s/ubph4qa6a00185w/corn.jpg?dl=0",
        title: 'Corn-flour-100gm',
        desc: "Corn flour use to increase the density of mixer",
        category: 'Baking Needs',
        price: 60,
    },
    {
        id: 57,
        img: "https://dl.dropboxusercontent.com/s/1vp0w1ofqd74eiv/csauce.jpg?dl=0",
        title: 'Chocolate Sause-200gm',
        desc: "Chocolate Sause is the fine ground brown Sause obtained from the partially or completely defatted portion of cocoa liquor or mass of fermented cocoa beans",
        category: 'Baking Needs',
        price: 200,
    },
    {
        id: 58,
        img: "https://dl.dropboxusercontent.com/s/0k193j6k2slsint/vessense.jpg?dl=0",
        title: 'Vanila Essence-20gm',
        desc: "Vanila essence used in making vanila cake",
        category: 'Baking Needs',
        price: 50,
    },
    {
        id: 59,
        img: "https://dl.dropboxusercontent.com/s/izi6qnk70wgmxas/chinigura.png?dl=0",
        title: 'Chini Gura-1kg',
        desc: "Premium Chinigura Loose Rice is selected from high quality rice. The health advantages of rice is its ability to produce and keep instant energy.",
        category: 'Daily cooking',
        price: 100,
    },
    {
        id: 60,
        img: "https://dl.dropboxusercontent.com/s/dohcrjr39fwatgk/egg.jpg?dl=0",
        title: 'Egg-1 dozen',
        desc: "Egg contains vitamins and protein, which together may promote brain development in children, help the nervous system function properly and aid cognitive performance in older adults",
        category: 'Daily cooking',
        price: 115,
    },
    {
        id: 61,
        img: "https://dl.dropboxusercontent.com/s/4eaglh85lx4xzmw/chicken.png?dl=0",
        title: 'Frozen Chicken Meat-1kg',
        desc: "Chicken contains vitamin B12 and choline, which together may promote brain development in children, help the nervous system function properly and aid cognitive performance in older adults",
        category: 'Daily cooking',
        price: 120,
    },
    {
        id: 62,
        img: "https://dl.dropboxusercontent.com/s/kzs4qjsfcadd15q/fish.jpg?dl=0",
        title: 'Frozen Rui Fish-1kg',
        desc: "Fish contains vitamin A and protein, which together may promote brain development in children, help the nervous system function properly and aid cognitive performance in older adults",
        category: 'Daily cooking',
        price: 200,
    },
    {
        id: 63,
        img: "https://dl.dropboxusercontent.com/s/71hc8b6zlurxftk/turmeric.png?dl=0",
        title: 'Tumeric Powder-200g',
        desc: "Made from the Finest Sources of Ingredients. BD Turmeric powder adds flavor to food, which explains its presence in curry powder",
        category: 'Daily cooking',
        price: 100,
    },
    {
        id: 64,
        img: "https://dl.dropboxusercontent.com/s/svx00abjytpclp5/tes.png?dl=0",
        title: 'Elach And Tespata-50g',
        desc: "The bay leaf is an aromatic leaf commonly used in cooking. It can be used whole, or as dried and ground. Bay leaves are a rich source of vitamin A, vitamin C, iron, potassium, calcium, and magnesium.",
        category: 'Daily cooking',
        price: 50,
    },
    {
        id: 65,
        img: "https://dl.dropboxusercontent.com/s/0j7y58l0ooctj0a/meat%20masala.png?dl=0",
        title: 'Mixed Meat Masala-50g',
        desc: "Radhuni meat Masala mix helps you prepare rich and aromatic meat Curry for an appetizing and flavorful dish in an easy manner at the comfort of your home",
        category: 'Daily cooking',
        price: 75,
    },
    {
        id: 66,
        img: "https://dl.dropboxusercontent.com/s/jyqxh6tx6ujcg5q/spray.jpg?dl=0",
        title: 'Dettol Disinfectant Spray-225ml',
        desc: "Variant: Dettol Disinfectant comes in Original Pine and Spring Blossom fragrance. All the Disinfectant spray comes in 225 ml.",
        category: 'Hygiene & essential',
        price: 350,
    },
    {
        id: 67,
        img: "https://dl.dropboxusercontent.com/s/epxfor1jtsz4f07/harpic.jpg?dl=0",
        title: 'Harpic liquid-500ml',
        desc: "Harpic Toilet Cleaning Liquid is a perfect cleaning solution for your bathroom . It cleans the stains and prevents from the germs and leave a fresh smell and sparkling clean . It comes with a easy way to lid and twist to open .To have a fresh toilet this is what you need",
        category: 'Hygiene & essential',
        price: 115,
    }, {
        id: 68,
        img: "https://dl.dropboxusercontent.com/s/cushv4ygl31wepf/cleaner.jpg?dl=0",
        title: 'Glass Cleaner-350ml',
        desc: "Mr. Brasso Glass & Household Cleaner is the leading among other glass cleaners . It goes on all types of glass and make them look like the new ones . It Is chlorine free and doesn't consist bleach . You can also use it on plastic , laminates ,windshield and etc.",
        category: 'Hygiene & essential',
        price: 145,
    }, {
        id: 69,
        img: "https://dl.dropboxusercontent.com/s/exyv5075oc7des2/lizol.jpg?dl=0",
        title: 'Lizol Surface Cleaner-500ml',
        desc: "Lizol Disinfectant Surface Cleaner Jasmine is a disinfectant floor cleaner. It Saves us from the germs and Prevents us from infections . It is 10 times effective than the other regular cleaners. Comes with a fragrance of jasmine leaving the bathroom with a fresh smell and removing stains and yellowness",
        category: 'Hygiene & essential',
        price: 150,
    },
    {
        id: 70,
        img: "https://dl.dropboxusercontent.com/s/0ifetpc03x85pl8/head.jpg?dl=0",
        title: 'Head And Shoulder-340ml',
        desc: "Head and shoulder long and healthy growth shampoo, nourishes the hair and helps hair grow long up to its full potential of 1.3 cm per month. Get set to flaunt your locks wherever you go buy Sunsilk long and healthy growth shampoo, right away",
        category: 'Hygiene & essential',
        price: 530,
    },


]


export default productData;


